server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanagement
    password: 12345
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update